import string

__CONSTANT = list(string.ascii_letters + string.digits) + [
    'Tab', 'Return', 'Left', 'Right', 'Up', 'Down', 'Home', 'End',
    'Print', 'Menu'
] + ['F' + str(i) for i in range(1, 13)]

CHARACTERS = {
    'Space': 'space',
    '!': 'exclam',
    '"': 'quotedbl',
    '#': 'numbersign',
    '$': 'dollar',
    '%': 'percent',
    '&': 'ampersand',
    "'": 'apostrophe',
    '(': 'parenleft',
    ')': 'parenright',
    '*': 'asterisk',
    '+': 'plus',
    ',': 'comma',
    '-': 'minus',
    '.': 'period',
    '/': 'slash',
    ':': 'colon',
    ';': 'semicolon',
    '<': 'less',
    '=': 'equal',
    '>': 'greater',
    '?': 'question',
    '@': 'at',
    '[': 'bracketleft',
    '\\': 'backslash',
    ']': 'bracketright',
    '^': 'asciicircum',
    '_': 'underscore',
    '`': 'grave',
    '{': 'braceleft',
    '|': 'bar',
    '}': 'braceright',
    '~': 'asciitilde',
    '¡': 'exclamdown',
    '¢': 'cent',
    '£': 'sterling',
    '¥': 'yen',
    '§': 'section',
    '¨': 'diaeresis',
    '©': 'copyright',
    'ª': 'ordfeminine',
    '«': 'guillemotleft',
    '¬': 'notsign',
    '®': 'registered',
    '°': 'degree',
    '±': 'plusminus',
    '²': 'twosuperior',
    '³': 'threesuperior',
    '´': 'acute',
    'µ': 'mu',
    '·': 'periodcentered',
    '¹': 'onesuperior',
    'º': 'masculine',
    '»': 'guillemotright',
    '¼': 'onequarter',
    '½': 'onehalf',
    '¾': 'threequarters',
    '¿': 'questiondown',
    'Æ': 'AE',
    'Ç': 'Ccedilla',
    'Ð': 'ETH',
    '×': 'multiply',
    'Ø': 'Oslash',
    'Þ': 'THORN',
    'ß': 'ssharp',
    'æ': 'ae',
    'ç': 'ccedilla',
    'ð': 'eth',
    '÷': 'division',
    'ø': 'oslash',
    'þ': 'thorn',
    'Ł': 'Lstroke',
    'ł': 'lstroke',
    'đ': 'dstroke',
    'Ħ': 'Hstroke',
    'ħ': 'hstroke',
    'ı': 'idotless',
    'ĸ': 'kra',
    'Ŧ': 'Tslash',
    'ŧ': 'tslash',
    'Ŋ': 'ENG',
    'ŋ': 'eng',
    '←': 'leftarrow',
    '↑': 'uparrow',
    '→': 'rightarrow',
    '↓': 'downarrow',
    '⅜': 'threeeighths',
    '⅞': 'seveneighths',
    '™': 'trademark',
    '‘': 'leftsinglequotemark',
    '’': 'rightsinglequotemark',
    '“': 'leftdoublequotemark',
    '”': 'rightdoublequotemark',
    'Ccedilla': 'ccedilla',
    'Esc': 'Escape',
    'PgUp': 'Prior',
    'PgDown': 'Next',
    'Ins': 'Insert',
    'Del': 'Delete',
    'CapsLock': 'Caps_Lock',
    'NumLock': 'Num_Lock',
    'ScrollLock': 'Scroll_Lock',
    'Backspace': 'BackSpace',
    'Backtab': 'Tab',
    'KP_+': 'KP_Add',
    'KP_-': 'KP_Subtract',
    'KP_*': 'KP_Multiply',
    'KP_/': 'KP_Divide',
    'KP_.': 'KP_Decimal',
    'KP_,': 'KP_Separator',
    'KP_Clear': 'KP_Begin',
    'KP_PgUp': 'KP_Prior',
    'KP_PgDown': 'KP_Next',
    'KP_Ins': 'KP_Insert',
    'KP_Del': 'KP_Delete'
}
CHARACTERS.update({c: c for c in __CONSTANT})

__DEAD_NAMES = ['grave', 'acute', 'circumflex', 'tilde', 'macron', 'breve',
       'abovedot', 'diaeresis', 'doubleacute', 'ogonek', 'belowdot',
       'hook', 'horn']
DEAD = {(0x1001250 + i): 'dead_' + __DEAD_NAMES[i]
            for i in range(len(__DEAD_NAMES))}
