# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sshkbm_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SSHKBMWindow(object):
    def setupUi(self, SSHKBMWindow):
        SSHKBMWindow.setObjectName("SSHKBMWindow")
        SSHKBMWindow.resize(1110, 634)
        self.centralwidget = QtWidgets.QWidget(SSHKBMWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setObjectName("tabWidget")
        self.connectionTab = QtWidgets.QWidget()
        self.connectionTab.setObjectName("connectionTab")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.connectionTab)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.connectionTab)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.hostField = QtWidgets.QLineEdit(self.connectionTab)
        self.hostField.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly)
        self.hostField.setObjectName("hostField")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.hostField)
        self.label_5 = QtWidgets.QLabel(self.connectionTab)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.portField = QtWidgets.QLineEdit(self.connectionTab)
        self.portField.setInputMethodHints(QtCore.Qt.ImhDigitsOnly|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhPreferNumbers)
        self.portField.setText("")
        self.portField.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.portField.setObjectName("portField")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.portField)
        self.label_3 = QtWidgets.QLabel(self.connectionTab)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.userField = QtWidgets.QLineEdit(self.connectionTab)
        self.userField.setInputMethodHints(QtCore.Qt.ImhLowercaseOnly|QtCore.Qt.ImhPreferLatin)
        self.userField.setObjectName("userField")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.userField)
        self.label_4 = QtWidgets.QLabel(self.connectionTab)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.passwordField = QtWidgets.QLineEdit(self.connectionTab)
        self.passwordField.setInputMethodHints(QtCore.Qt.ImhHiddenText|QtCore.Qt.ImhNoAutoUppercase|QtCore.Qt.ImhNoPredictiveText|QtCore.Qt.ImhSensitiveData)
        self.passwordField.setEchoMode(QtWidgets.QLineEdit.Password)
        self.passwordField.setObjectName("passwordField")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.passwordField)
        self.displayField = QtWidgets.QLineEdit(self.connectionTab)
        self.displayField.setObjectName("displayField")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.displayField)
        self.connectButton = QtWidgets.QPushButton(self.connectionTab)
        self.connectButton.setObjectName("connectButton")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.connectButton)
        self.label_6 = QtWidgets.QLabel(self.connectionTab)
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.gridLayout_5.addLayout(self.formLayout, 0, 1, 1, 1)
        self.tabWidget.addTab(self.connectionTab, "")
        self.keyboardTab = QtWidgets.QWidget()
        self.keyboardTab.setFocusPolicy(QtCore.Qt.NoFocus)
        self.keyboardTab.setObjectName("keyboardTab")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.keyboardTab)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.keyboardTab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setWordWrap(True)
        self.label_7.setObjectName("label_7")
        self.gridLayout_7.addWidget(self.label_7, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 1, 0, 1, 1)
        self.lastKeyLabel = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setFamily("Sans Serif")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.lastKeyLabel.setFont(font)
        self.lastKeyLabel.setText("")
        self.lastKeyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.lastKeyLabel.setObjectName("lastKeyLabel")
        self.gridLayout_7.addWidget(self.lastKeyLabel, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 4, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ignoreModifiersCheck = QtWidgets.QCheckBox(self.frame_4)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ignoreModifiersCheck.setFont(font)
        self.ignoreModifiersCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ignoreModifiersCheck.setChecked(False)
        self.ignoreModifiersCheck.setObjectName("ignoreModifiersCheck")
        self.horizontalLayout_2.addWidget(self.ignoreModifiersCheck)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.leftArrowBtn = QtWidgets.QPushButton(self.frame_8)
        self.leftArrowBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.leftArrowBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.leftArrowBtn.setObjectName("leftArrowBtn")
        self.horizontalLayout_8.addWidget(self.leftArrowBtn)
        self.downArrowBtn = QtWidgets.QPushButton(self.frame_8)
        self.downArrowBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.downArrowBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.downArrowBtn.setObjectName("downArrowBtn")
        self.horizontalLayout_8.addWidget(self.downArrowBtn)
        self.upArrowBtn = QtWidgets.QPushButton(self.frame_8)
        self.upArrowBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.upArrowBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.upArrowBtn.setObjectName("upArrowBtn")
        self.horizontalLayout_8.addWidget(self.upArrowBtn)
        self.rightArrowBtn = QtWidgets.QPushButton(self.frame_8)
        self.rightArrowBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.rightArrowBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.rightArrowBtn.setObjectName("rightArrowBtn")
        self.horizontalLayout_8.addWidget(self.rightArrowBtn)
        self.horizontalLayout_2.addWidget(self.frame_8)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_4, 6, 0, 1, 1)
        self.lastKeyTitleLabel = QtWidgets.QLabel(self.frame_2)
        self.lastKeyTitleLabel.setText("")
        self.lastKeyTitleLabel.setObjectName("lastKeyTitleLabel")
        self.gridLayout_7.addWidget(self.lastKeyTitleLabel, 2, 0, 1, 1)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.shiftCheck = QtWidgets.QCheckBox(self.frame_3)
        self.shiftCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.shiftCheck.setObjectName("shiftCheck")
        self.horizontalLayout.addWidget(self.shiftCheck)
        self.ctrlCheck = QtWidgets.QCheckBox(self.frame_3)
        self.ctrlCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.ctrlCheck.setObjectName("ctrlCheck")
        self.horizontalLayout.addWidget(self.ctrlCheck)
        self.superCheck = QtWidgets.QCheckBox(self.frame_3)
        self.superCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.superCheck.setObjectName("superCheck")
        self.horizontalLayout.addWidget(self.superCheck)
        self.altCheck = QtWidgets.QCheckBox(self.frame_3)
        self.altCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.altCheck.setObjectName("altCheck")
        self.horizontalLayout.addWidget(self.altCheck)
        self.altGrCheck = QtWidgets.QCheckBox(self.frame_3)
        self.altGrCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.altGrCheck.setObjectName("altGrCheck")
        self.horizontalLayout.addWidget(self.altGrCheck)
        self.composeCheck = QtWidgets.QCheckBox(self.frame_3)
        self.composeCheck.setFocusPolicy(QtCore.Qt.NoFocus)
        self.composeCheck.setObjectName("composeCheck")
        self.horizontalLayout.addWidget(self.composeCheck)
        self.gridLayout_8.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_3, 5, 0, 1, 1)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.spaceBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.spaceBtn.setFont(font)
        self.spaceBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.spaceBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.spaceBtn.setObjectName("spaceBtn")
        self.horizontalLayout_3.addWidget(self.spaceBtn)
        self.escBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.escBtn.setFont(font)
        self.escBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.escBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.escBtn.setObjectName("escBtn")
        self.horizontalLayout_3.addWidget(self.escBtn)
        self.tabBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabBtn.setFont(font)
        self.tabBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.tabBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabBtn.setObjectName("tabBtn")
        self.horizontalLayout_3.addWidget(self.tabBtn)
        self.capsBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.capsBtn.setFont(font)
        self.capsBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.capsBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.capsBtn.setObjectName("capsBtn")
        self.horizontalLayout_3.addWidget(self.capsBtn)
        self.insBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.insBtn.setFont(font)
        self.insBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.insBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.insBtn.setObjectName("insBtn")
        self.horizontalLayout_3.addWidget(self.insBtn)
        self.delBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.delBtn.setFont(font)
        self.delBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.delBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.delBtn.setObjectName("delBtn")
        self.horizontalLayout_3.addWidget(self.delBtn)
        self.prtscrBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.prtscrBtn.setFont(font)
        self.prtscrBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.prtscrBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prtscrBtn.setObjectName("prtscrBtn")
        self.horizontalLayout_3.addWidget(self.prtscrBtn)
        self.pgupBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pgupBtn.setFont(font)
        self.pgupBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pgupBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pgupBtn.setObjectName("pgupBtn")
        self.horizontalLayout_3.addWidget(self.pgupBtn)
        self.pgdnBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pgdnBtn.setFont(font)
        self.pgdnBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.pgdnBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pgdnBtn.setObjectName("pgdnBtn")
        self.horizontalLayout_3.addWidget(self.pgdnBtn)
        self.homeBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.homeBtn.setFont(font)
        self.homeBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.homeBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.homeBtn.setObjectName("homeBtn")
        self.horizontalLayout_3.addWidget(self.homeBtn)
        self.endBtn = QtWidgets.QPushButton(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.endBtn.setFont(font)
        self.endBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.endBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.endBtn.setObjectName("endBtn")
        self.horizontalLayout_3.addWidget(self.endBtn)
        self.gridLayout_10.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.frame_5, 13, 0, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_2)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.f1Btn = QtWidgets.QPushButton(self.frame_7)
        self.f1Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f1Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f1Btn.setObjectName("f1Btn")
        self.horizontalLayout_6.addWidget(self.f1Btn)
        self.f2Btn = QtWidgets.QPushButton(self.frame_7)
        self.f2Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f2Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f2Btn.setObjectName("f2Btn")
        self.horizontalLayout_6.addWidget(self.f2Btn)
        self.f3Btn = QtWidgets.QPushButton(self.frame_7)
        self.f3Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f3Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f3Btn.setObjectName("f3Btn")
        self.horizontalLayout_6.addWidget(self.f3Btn)
        self.f4Btn = QtWidgets.QPushButton(self.frame_7)
        self.f4Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f4Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f4Btn.setObjectName("f4Btn")
        self.horizontalLayout_6.addWidget(self.f4Btn)
        self.f5Btn = QtWidgets.QPushButton(self.frame_7)
        self.f5Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f5Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f5Btn.setObjectName("f5Btn")
        self.horizontalLayout_6.addWidget(self.f5Btn)
        self.f6Btn = QtWidgets.QPushButton(self.frame_7)
        self.f6Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f6Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f6Btn.setObjectName("f6Btn")
        self.horizontalLayout_6.addWidget(self.f6Btn)
        self.f7Btn = QtWidgets.QPushButton(self.frame_7)
        self.f7Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f7Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f7Btn.setObjectName("f7Btn")
        self.horizontalLayout_6.addWidget(self.f7Btn)
        self.f8Btn = QtWidgets.QPushButton(self.frame_7)
        self.f8Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f8Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f8Btn.setObjectName("f8Btn")
        self.horizontalLayout_6.addWidget(self.f8Btn)
        self.f9Btn = QtWidgets.QPushButton(self.frame_7)
        self.f9Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f9Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f9Btn.setObjectName("f9Btn")
        self.horizontalLayout_6.addWidget(self.f9Btn)
        self.f10Btn = QtWidgets.QPushButton(self.frame_7)
        self.f10Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f10Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f10Btn.setObjectName("f10Btn")
        self.horizontalLayout_6.addWidget(self.f10Btn)
        self.f11Btn = QtWidgets.QPushButton(self.frame_7)
        self.f11Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f11Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f11Btn.setObjectName("f11Btn")
        self.horizontalLayout_6.addWidget(self.f11Btn)
        self.f12Btn = QtWidgets.QPushButton(self.frame_7)
        self.f12Btn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.f12Btn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.f12Btn.setObjectName("f12Btn")
        self.horizontalLayout_6.addWidget(self.f12Btn)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.gridLayout_7.addWidget(self.frame_7, 14, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.muteBtn = QtWidgets.QPushButton(self.frame_6)
        self.muteBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.muteBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.muteBtn.setObjectName("muteBtn")
        self.horizontalLayout_5.addWidget(self.muteBtn)
        self.volDownBtn = QtWidgets.QPushButton(self.frame_6)
        self.volDownBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.volDownBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.volDownBtn.setObjectName("volDownBtn")
        self.horizontalLayout_5.addWidget(self.volDownBtn)
        self.volUpBtn = QtWidgets.QPushButton(self.frame_6)
        self.volUpBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.volUpBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.volUpBtn.setObjectName("volUpBtn")
        self.horizontalLayout_5.addWidget(self.volUpBtn)
        self.playBtn = QtWidgets.QPushButton(self.frame_6)
        self.playBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.playBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.playBtn.setObjectName("playBtn")
        self.horizontalLayout_5.addWidget(self.playBtn)
        self.stopBtn = QtWidgets.QPushButton(self.frame_6)
        self.stopBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.stopBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.stopBtn.setObjectName("stopBtn")
        self.horizontalLayout_5.addWidget(self.stopBtn)
        self.prevBtn = QtWidgets.QPushButton(self.frame_6)
        self.prevBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.prevBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.prevBtn.setObjectName("prevBtn")
        self.horizontalLayout_5.addWidget(self.prevBtn)
        self.nextBtn = QtWidgets.QPushButton(self.frame_6)
        self.nextBtn.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.nextBtn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nextBtn.setObjectName("nextBtn")
        self.horizontalLayout_5.addWidget(self.nextBtn)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.gridLayout_7.addWidget(self.frame_6, 15, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.keyboardTab, "")
        self.typingTab = QtWidgets.QWidget()
        self.typingTab.setObjectName("typingTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.typingTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.typingField = QtWidgets.QPlainTextEdit(self.typingTab)
        self.typingField.setObjectName("typingField")
        self.verticalLayout_2.addWidget(self.typingField)
        self.frame = QtWidgets.QFrame(self.typingTab)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(171, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.sendTextButton = QtWidgets.QPushButton(self.frame)
        self.sendTextButton.setObjectName("sendTextButton")
        self.gridLayout_3.addWidget(self.sendTextButton, 0, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.frame)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem5)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.typingTab, "")
        self.mouseTab = QtWidgets.QWidget()
        self.mouseTab.setEnabled(True)
        self.mouseTab.setObjectName("mouseTab")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.mouseTab)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_9 = QtWidgets.QFrame(self.mouseTab)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.mousePicture = QtWidgets.QLabel(self.frame_9)
        self.mousePicture.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mousePicture.sizePolicy().hasHeightForWidth())
        self.mousePicture.setSizePolicy(sizePolicy)
        self.mousePicture.setMaximumSize(QtCore.QSize(400, 400))
        self.mousePicture.setCursor(QtGui.QCursor(QtCore.Qt.CrossCursor))
        self.mousePicture.setMouseTracking(True)
        self.mousePicture.setText("")
        self.mousePicture.setPixmap(QtGui.QPixmap(":/mouse-bg/img/mouse-bg.svg"))
        self.mousePicture.setScaledContents(True)
        self.mousePicture.setObjectName("mousePicture")
        self.verticalLayout_4.addWidget(self.mousePicture)
        self.horizontalLayout_9.addWidget(self.frame_9)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_9)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.tabWidget.addTab(self.mouseTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        SSHKBMWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(SSHKBMWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName("statusbar")
        SSHKBMWindow.setStatusBar(self.statusbar)

        self.retranslateUi(SSHKBMWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(SSHKBMWindow)
        SSHKBMWindow.setTabOrder(self.hostField, self.portField)
        SSHKBMWindow.setTabOrder(self.portField, self.userField)
        SSHKBMWindow.setTabOrder(self.userField, self.passwordField)
        SSHKBMWindow.setTabOrder(self.passwordField, self.connectButton)
        SSHKBMWindow.setTabOrder(self.connectButton, self.displayField)
        SSHKBMWindow.setTabOrder(self.displayField, self.sendTextButton)
        SSHKBMWindow.setTabOrder(self.sendTextButton, self.typingField)

    def retranslateUi(self, SSHKBMWindow):
        _translate = QtCore.QCoreApplication.translate
        SSHKBMWindow.setWindowTitle(_translate("SSHKBMWindow", "SSHKBM"))
        self.label_2.setText(_translate("SSHKBMWindow", "Host"))
        self.label_5.setText(_translate("SSHKBMWindow", "Port"))
        self.label_3.setText(_translate("SSHKBMWindow", "User"))
        self.label_4.setText(_translate("SSHKBMWindow", "Password"))
        self.displayField.setText(_translate("SSHKBMWindow", ":0"))
        self.connectButton.setText(_translate("SSHKBMWindow", "Connect"))
        self.label_6.setText(_translate("SSHKBMWindow", "Display"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.connectionTab), _translate("SSHKBMWindow", "Connection"))
        self.label_7.setText(_translate("SSHKBMWindow", "Keys pressed inside this tab will be sent to the remote computer."))
        self.ignoreModifiersCheck.setText(_translate("SSHKBMWindow", "Only the modifiers above"))
        self.leftArrowBtn.setText(_translate("SSHKBMWindow", "←"))
        self.leftArrowBtn.setProperty("Key", _translate("SSHKBMWindow", "Left"))
        self.downArrowBtn.setText(_translate("SSHKBMWindow", "↓"))
        self.downArrowBtn.setProperty("Key", _translate("SSHKBMWindow", "Down"))
        self.upArrowBtn.setText(_translate("SSHKBMWindow", "↑"))
        self.upArrowBtn.setProperty("Key", _translate("SSHKBMWindow", "Up"))
        self.rightArrowBtn.setText(_translate("SSHKBMWindow", "→"))
        self.rightArrowBtn.setProperty("Key", _translate("SSHKBMWindow", "Right"))
        self.shiftCheck.setText(_translate("SSHKBMWindow", "Shift"))
        self.ctrlCheck.setText(_translate("SSHKBMWindow", "Ctrl"))
        self.superCheck.setText(_translate("SSHKBMWindow", "Super"))
        self.altCheck.setText(_translate("SSHKBMWindow", "Alt"))
        self.altGrCheck.setText(_translate("SSHKBMWindow", "Alt Gr"))
        self.composeCheck.setText(_translate("SSHKBMWindow", "Compose"))
        self.spaceBtn.setText(_translate("SSHKBMWindow", "Space"))
        self.spaceBtn.setProperty("Key", _translate("SSHKBMWindow", "space"))
        self.escBtn.setText(_translate("SSHKBMWindow", "Esc"))
        self.escBtn.setProperty("Key", _translate("SSHKBMWindow", "Escape"))
        self.tabBtn.setText(_translate("SSHKBMWindow", "Tab"))
        self.tabBtn.setProperty("Key", _translate("SSHKBMWindow", "Tab"))
        self.capsBtn.setText(_translate("SSHKBMWindow", "Caps"))
        self.capsBtn.setProperty("Key", _translate("SSHKBMWindow", "Caps_Lock"))
        self.insBtn.setText(_translate("SSHKBMWindow", "Ins"))
        self.insBtn.setProperty("Key", _translate("SSHKBMWindow", "Insert"))
        self.delBtn.setText(_translate("SSHKBMWindow", "Del"))
        self.delBtn.setProperty("Key", _translate("SSHKBMWindow", "Delete"))
        self.prtscrBtn.setText(_translate("SSHKBMWindow", "PrtScr"))
        self.prtscrBtn.setProperty("Key", _translate("SSHKBMWindow", "Print"))
        self.pgupBtn.setText(_translate("SSHKBMWindow", "PgUp"))
        self.pgupBtn.setProperty("Key", _translate("SSHKBMWindow", "Prior"))
        self.pgdnBtn.setText(_translate("SSHKBMWindow", "PgDn"))
        self.pgdnBtn.setProperty("Key", _translate("SSHKBMWindow", "Next"))
        self.homeBtn.setText(_translate("SSHKBMWindow", "Home"))
        self.homeBtn.setProperty("Key", _translate("SSHKBMWindow", "Home"))
        self.endBtn.setText(_translate("SSHKBMWindow", "End"))
        self.endBtn.setProperty("Key", _translate("SSHKBMWindow", "End"))
        self.f1Btn.setText(_translate("SSHKBMWindow", "F1"))
        self.f1Btn.setProperty("Key", _translate("SSHKBMWindow", "F1"))
        self.f2Btn.setText(_translate("SSHKBMWindow", "F2"))
        self.f2Btn.setProperty("Key", _translate("SSHKBMWindow", "F2"))
        self.f3Btn.setText(_translate("SSHKBMWindow", "F3"))
        self.f3Btn.setProperty("Key", _translate("SSHKBMWindow", "F3"))
        self.f4Btn.setText(_translate("SSHKBMWindow", "F4"))
        self.f4Btn.setProperty("Key", _translate("SSHKBMWindow", "F4"))
        self.f5Btn.setText(_translate("SSHKBMWindow", "F5"))
        self.f5Btn.setProperty("Key", _translate("SSHKBMWindow", "F5"))
        self.f6Btn.setText(_translate("SSHKBMWindow", "F6"))
        self.f6Btn.setProperty("Key", _translate("SSHKBMWindow", "F6"))
        self.f7Btn.setText(_translate("SSHKBMWindow", "F7"))
        self.f7Btn.setProperty("Key", _translate("SSHKBMWindow", "F7"))
        self.f8Btn.setText(_translate("SSHKBMWindow", "F8"))
        self.f8Btn.setProperty("Key", _translate("SSHKBMWindow", "F8"))
        self.f9Btn.setText(_translate("SSHKBMWindow", "F9"))
        self.f9Btn.setProperty("Key", _translate("SSHKBMWindow", "F9"))
        self.f10Btn.setText(_translate("SSHKBMWindow", "F10"))
        self.f10Btn.setProperty("Key", _translate("SSHKBMWindow", "F10"))
        self.f11Btn.setText(_translate("SSHKBMWindow", "F11"))
        self.f11Btn.setProperty("Key", _translate("SSHKBMWindow", "F11"))
        self.f12Btn.setText(_translate("SSHKBMWindow", "F12"))
        self.f12Btn.setProperty("Key", _translate("SSHKBMWindow", "F12"))
        self.muteBtn.setText(_translate("SSHKBMWindow", "Mute"))
        self.muteBtn.setProperty("Key", _translate("SSHKBMWindow", "XF86AudioMute"))
        self.volDownBtn.setText(_translate("SSHKBMWindow", "Vol–"))
        self.volDownBtn.setProperty("Key", _translate("SSHKBMWindow", "XF86AudioLowerVolume"))
        self.volUpBtn.setText(_translate("SSHKBMWindow", "Vol+"))
        self.volUpBtn.setProperty("Key", _translate("SSHKBMWindow", "XF86AudioRaiseVolume"))
        self.playBtn.setText(_translate("SSHKBMWindow", "Play"))
        self.playBtn.setProperty("Key", _translate("SSHKBMWindow", "XF86AudioPlay"))
        self.stopBtn.setText(_translate("SSHKBMWindow", "Stop"))
        self.stopBtn.setProperty("Key", _translate("SSHKBMWindow", "XF86AudioStop"))
        self.prevBtn.setText(_translate("SSHKBMWindow", "Prev"))
        self.prevBtn.setProperty("Key", _translate("SSHKBMWindow", "XF86AudioPrev"))
        self.nextBtn.setText(_translate("SSHKBMWindow", "Next"))
        self.nextBtn.setProperty("Key", _translate("SSHKBMWindow", "XF86AudioNext"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.keyboardTab), _translate("SSHKBMWindow", "Keyboard"))
        self.sendTextButton.setText(_translate("SSHKBMWindow", "Send text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.typingTab), _translate("SSHKBMWindow", "Typing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.mouseTab), _translate("SSHKBMWindow", "Mouse"))

from ui import bg_rc
